version: "3.8"

services:
  mongodb:
    image: percona/percona-server-mongodb:latest
    container_name: percona-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./certs:/etc/mongo/certs
    command: >
      mongod --enableEncryption
      --kmipServerName host.docker.internal
      --kmipPort 5696
      --kmipServerCAFile /etc/mongo/certs/client-chain.pem
      --kmipClientCertificateFile /etc/mongo/certs/client-cert.pem

volumes:
  mongo_data:
